apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wordpress
      app.kubernetes.io/name: wordpress
  template:
    metadata:
      labels:
        app: wordpress
        app.kubernetes.io/name: wordpress
    spec:
      containers:
        - name: wordpress
          image: wordpress:latest
          ports:
            - containerPort: 80
          env:
            - name: WORDPRESS_DB_HOST
              value: brand-media-kitqa.cttbr9nhjjj8.us-east-1.rds.amazonaws.com:3306
            - name: WORDPRESS_DB_USER
              value: wp_admin
            - name: WORDPRESS_DB_PASSWORD
              value: BrAAe4_k11Tte_d3vQa13
            - name: WORDPRESS_DB_NAME
              value: brand_media_kit_wp